#!/bin/sh
# install.sh — install a zcode-rs payload into a user-chosen prefix.
#
# Usage:
#   install.sh [--from PAYLOAD_DIR] [PREFIX]     install (default ~/.zcode/rust-bin)
#   install.sh --uninstall [PREFIX]              remove previously installed files
#   install.sh --help
#
# Payload resolution (first match wins):
#   1. --from DIR (a dist/zcode-rs-<ver>/ payload, incl. cross-built dist-rs/)
#   2. the directory containing this install.sh, if it is itself a payload
#      (i.e. running from an unpacked tarball)
#   3. newest dist/zcode-rs-*/ next to the repo checkout (../dist/)
#
# Installed layout (idempotent — safe to re-run):
#   <prefix>/bin/zcode        wrapper: exports ZCODE_NODE_BUNDLE=<prefix>/runtime/zcode.cjs
#                             (relative entries resolve vs <prefix>/libexec), execs the binary
#   <prefix>/libexec/zcode    raw native binary
#   <prefix>/runtime/zcode.cjs  Node fallback sidecar
#   <prefix>/zcode.env        install defaults (sourced by the wrapper)
#   <prefix>/.zcode-rs-files  manifest used by --uninstall
set -eu

USAGE=$(sed -n '2,25p' "$0")
SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)

PAYLOAD=""
PREFIX=""
UNINSTALL=0
while [ $# -gt 0 ]; do
  case $1 in
    --uninstall) UNINSTALL=1 ;;
    --from) [ -n "${2:-}" ] || { echo "error: --from needs a directory" >&2; exit 2; }
            PAYLOAD=$2; shift ;;
    -h|--help) printf '%s\n' "$USAGE"; exit 0 ;;
    -*) echo "error: unknown option: $1" >&2; exit 2 ;;
    *)  [ -z "$PREFIX" ] || { echo "error: multiple prefixes given" >&2; exit 2; }
        PREFIX=$1 ;;
  esac
  shift
done
PREFIX="${PREFIX:-$HOME/.zcode/rust-bin}"

# ---------- uninstall ----------
if [ "$UNINSTALL" -eq 1 ]; then
  if [ ! -d "$PREFIX" ]; then
    echo "nothing to uninstall at $PREFIX"
    exit 0
  fi
  if [ -f "$PREFIX/.zcode-rs-files" ]; then
    while IFS= read -r rel; do
      [ -n "$rel" ] && rm -f "$PREFIX/$rel"
    done < "$PREFIX/.zcode-rs-files"
  else
    # no manifest (very old install): remove the known managed files
    rm -f "$PREFIX/bin/zcode" "$PREFIX/libexec/zcode" "$PREFIX/runtime/zcode.cjs" \
          "$PREFIX/zcode.env" "$PREFIX/README" "$PREFIX/install.sh" "$PREFIX/.zcode-rs-files"
  fi
  for d in "$PREFIX/bin" "$PREFIX/libexec" "$PREFIX/runtime"; do
    rmdir "$d" 2>/dev/null || true
  done
  rmdir "$PREFIX" 2>/dev/null || true   # only succeeds when the prefix is now empty
  echo "uninstalled zcode-rs from $PREFIX"
  echo "reminder: drop the 'export PATH=...' line from your shell rc if present"
  exit 0
fi

# ---------- locate payload ----------
if [ -z "$PAYLOAD" ]; then
  if [ -f "$SCRIPT_DIR/bin/zcode" ] && [ -f "$SCRIPT_DIR/runtime/zcode.cjs" ]; then
    PAYLOAD=$SCRIPT_DIR
  else
    for d in "$SCRIPT_DIR"/../dist/zcode-rs-*; do
      if [ -f "$d/bin/zcode" ] && [ -f "$d/runtime/zcode.cjs" ]; then PAYLOAD=$d; fi
    done
  fi
fi
[ -n "$PAYLOAD" ] || {
  echo "error: no payload found — run scripts/package-rs.sh first, or pass --from DIR" >&2
  exit 1
}
for f in bin/zcode runtime/zcode.cjs zcode.env; do
  [ -e "$PAYLOAD/$f" ] || { echo "error: payload $PAYLOAD is missing $f" >&2; exit 1; }
done

# ---------- install ----------
mkdir -p "$PREFIX/bin" "$PREFIX/libexec" "$PREFIX/runtime"

WRAP="$PREFIX/bin/zcode"
if [ -e "$WRAP" ] && ! grep -q 'zcode-rs wrapper' "$WRAP" 2>/dev/null; then
  echo "error: $WRAP exists and was not installed by zcode-rs." >&2
  echo "  pick another prefix or remove that file first (never clobber foreign files)." >&2
  exit 1
fi

cp -f "$PAYLOAD/bin/zcode" "$PREFIX/libexec/zcode"
chmod 755 "$PREFIX/libexec/zcode"
cp -f "$PAYLOAD/runtime/zcode.cjs" "$PREFIX/runtime/zcode.cjs"
if [ -f "$PAYLOAD/zcode.env" ]; then cp -f "$PAYLOAD/zcode.env" "$PREFIX/zcode.env"; fi
if [ -f "$PAYLOAD/README" ]; then cp -f "$PAYLOAD/README" "$PREFIX/README"; fi
if [ -f "$PAYLOAD/install.sh" ]; then cp -f "$PAYLOAD/install.sh" "$PREFIX/install.sh"; fi

# Wrapper: fully relocatable (resolves everything from $0), sources zcode.env,
# then execs the native binary with all args unchanged.
cat > "$WRAP" <<'EOF'
#!/bin/sh
# zcode-rs wrapper (generated by zcode-rs/scripts/install.sh — do not edit).
# Exports ZCODE_NODE_BUNDLE (relative entries resolve against the binary's
# directory) and execs the native binary; all arguments pass through.
ZCODE_ROOT=$(CDPATH='' cd -- "$(dirname -- "$0")/.." 2>/dev/null && pwd -P) \
  || ZCODE_ROOT=$(dirname -- "$0")/..
[ -f "$ZCODE_ROOT/zcode.env" ] && . "$ZCODE_ROOT/zcode.env"
ZCODE_BIN="$ZCODE_ROOT/libexec/zcode"
if [ -n "${ZCODE_NODE_BUNDLE:-}" ]; then
  case $ZCODE_NODE_BUNDLE in
    /*) ;;
    *)
      if ! ZCODE_BIN_DIR=$(CDPATH='' cd -- "$(dirname -- "$ZCODE_BIN")" 2>/dev/null && pwd -P); then
        ZCODE_BIN_DIR=$(dirname -- "$ZCODE_BIN")
      fi
      ZCODE_NODE_BUNDLE="$ZCODE_BIN_DIR/$ZCODE_NODE_BUNDLE"
      ;;
  esac
  export ZCODE_NODE_BUNDLE
fi
exec "$ZCODE_BIN" "$@"
EOF
chmod 755 "$WRAP"

# Manifest for idempotent uninstalls.
cat > "$PREFIX/.zcode-rs-files" <<'EOF'
.zcode-rs-files
README
bin/zcode
install.sh
libexec/zcode
runtime/zcode.cjs
zcode.env
EOF

# ---------- verify + hint ----------
VER=$("$WRAP" --version | head -n1)
echo "installed zcode-rs $VER -> $PREFIX (payload: $PAYLOAD)"
echo
echo "Add to PATH:"
echo "  export PATH=\"$PREFIX/bin:\$PATH\"   # ~/.zshrc or ~/.bashrc"
echo
echo "Uninstall:"
echo "  $0 --uninstall $PREFIX"
echo "  (or, if this prefix is dedicated to zcode-rs: rm -rf $PREFIX)"
